package com.symmetricalpalmtree.soil.crypto

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.util.Locale

class RawKeyDerivationTest {

    @Test
    fun hex_isLowercaseAscii_localeIndependent() {
        val saved = Locale.getDefault()
        try {
            Locale.setDefault(Locale("ar", "EG"))
            val hex = RawKeyDerivation.toHex(byteArrayOf(0x00, 0x0A, 0x7F, 0xFF.toByte()))
            assertEquals("000a7fff", hex)
            assertTrue(hex.all { it in '0'..'9' || it in 'a'..'f' })
        } finally {
            Locale.setDefault(saved)
        }
    }

    @Test
    fun rawKeyLiteral_shape() {
        assertEquals("x'0102'", RawKeyDerivation.rawKeyLiteral(byteArrayOf(1, 2)))
    }

    @Test
    fun pbkdf2_matchesStandardVector() {
        // PBKDF2-HMAC-SHA512("password", "salt", 1, 64) — first 32 bytes of the published vector.
        val out = RawKeyDerivation.pbkdf2HmacSha512("password".toByteArray(), "salt".toByteArray(), 1, 64)
        assertEquals(
            "867f70cf1ade02cff3752599a3a53dc4af34c7a669815ae5d513554e1c8cf252",
            RawKeyDerivation.toHex(out.copyOf(32)),
        )
    }

    /** Full-strength vector at SQLCipher parameters — generated by Paper's implementation and
     *  independently confirmed with Python's `hashlib.pbkdf2_hmac` (byte-compat proof). */
    @Test
    fun pbkdf2_fullIterations_matchesFamilyVector() {
        val salt = ByteArray(16) { (it * 7 + 1).toByte() }
        val key = RawKeyDerivation.pbkdf2HmacSha512(
            SoilCrypto.keyBytes("NSPT-R1FX-TEST-ONLY-0000-1111-2222-3333-4444"),
            salt, RawKeyDerivation.KDF_ITER, RawKeyDerivation.KEY_LEN,
        )
        assertEquals("4784bd3cf49f4cd8437f3fbca7c7c71a25a235d27c7eb5eea3fab223c272370a", RawKeyDerivation.toHex(key))
    }

    @Test
    fun deriveKey_platformAndLoopAgree() {
        // deriveKey prefers the platform's PBKDF2 (one native call) and falls back to the loop; the
        // two must be byte-identical for ASCII and non-ASCII passphrases alike, or a cached raw
        // key would stop opening a file it once opened.
        val salt = ByteArray(RawKeyDerivation.SALT_LEN) { (it * 7 + 3).toByte() }
        val file = java.io.File.createTempFile("salt", ".soil").apply { writeBytes(salt); deleteOnExit() }
        for (pass in listOf("NSPT-1YDE-38ZS", "pässwörd ✓ 日本")) {
            val loop = RawKeyDerivation.pbkdf2HmacSha512(
                com.symmetricalpalmtree.soil.crypto.SoilCrypto.keyBytes(pass), salt, RawKeyDerivation.KDF_ITER, RawKeyDerivation.KEY_LEN)
            org.junit.Assert.assertArrayEquals(pass, loop, RawKeyDerivation.deriveKey(file, pass))
        }
    }

    @Test
    fun constants_areStockSqlcipher4() {
        assertEquals(256_000, RawKeyDerivation.KDF_ITER)
        assertEquals(32, RawKeyDerivation.KEY_LEN)
        assertEquals(16, RawKeyDerivation.SALT_LEN)
    }
}
